---
services:
  nfqws-build:
    build:
      context: .
    environment:
      - MAKEFLAGS=-j$(nproc)
    volumes:
      - ./openwrt-feed:/build/openwrt-feed
      - ./bin:/build/bin
    command: >
      bash -c "
        echo src-link local /build/openwrt-feed >> feeds.conf.default &&
        ./scripts/feeds update packages base local &&
        ./scripts/feeds install mss-nfqws &&
        make defconfig &&
        make package/mss-nfqws/compile
      "
