#!/bin/sh
nfqwspid="$(pidof nfqws)"
iface="$(grep 00000000 /proc/net/route | awk 'NR==1 {print $1}')"

case "$1" in
    start)
        nft add table ip mss-nfqws

        nft 'create chain ip mss-nfqws nfq {\
            type filter hook postrouting priority mangle;\
            policy accept;\
        }'

        nft add rule ip mss-nfqws nfq \
            oifname "${iface}" tcp dport \{80,443\} \
            ct original packets 1-4                 \
            mark and 0x40000000 != 0x40000000       \
            queue num 200 bypass

        nfqws \
            --uid=0:0                      \
            --qnum=200                     \
            --dpi-desync-fwmark=0x40000000 \
            --wssize=1:6                   \
            --hostcase                     \
            --hostspell=hoST               \
            --hostnospace                  \
            --domcase                      \
            --dpi-desync=fake              \
            --dpi-desync-fooling=md5sig    \
            --dpi-desync-retrans=1         \
            --dpi-desync-skip-nosni=0      \
            --dpi-desync-ttl=6             \
            --daemon
    ;;
    stop)
        nft delete table ip mss-nfqws || true

        for i in ${nfqwspid}; do
            kill -TERM "${i}" || kill -KILL "${i}" || true
        done
    ;;
esac
